### ISSUE TITLE
Add weather to archive file

### ISSUE THREAD

**Issue by thaaophz** [kautsig/org-weather#3]
It would be nice to archive the weather string to an org-file, e.g. weather.org_archive.
So it would be possible to look how the weather was e.g. one year ago by adding the the org_archive files to the agenda view.

Sadly I'm not a lisp-programmer :(

**Comment by kautsig** [comment]
Hey thaaophz, 
thanks for your suggestion, I really appreciate it.  A feature like this this would require quite an amount of work, I'm not planning to do at the moment. 


Because I'm also not a lisp programmer (I was just playing around when implementing this), if I had to implement saving and updating org files like this, I'd probably implement it using python and run from a cronjob, like memacs does. 

Sorry, for not being helpful.
